[project]
name = "helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "eth-abi>=5.2.0",
    "eth-keys>=0.7.0",
    "pysha3>=1.0.2",
]
