# .github/workflows/ci.yml
name: Python CI

on:
  push:
    branches: [ main, master ] # Adjust if your main branch has a different name
  pull_request:
    branches: [ main, master ] # Adjust if your main branch has a different name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify your desired Python version

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash
    
    - name: activate uv
      run: uv venv
      shell: bash

    - name: Install dependencies
      run: |
        uv pip install -e .[dev]
        # If you don't use optional dev dependencies, use this instead:
        # uv pip install --system -e .
        # uv pip install --system pytest ruff click # Add other dev tools if needed
      shell: bash

    - name: Lint with Ruff
      run: uv run ruff check .
      shell: bash

    - name: Run tests with Pytest
      run: uv run pytest -v
      shell: bash 